name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-test:
    name: Run unit tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP environment
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: phpunit:9

      - name: Prepare files
        run: |
          sed "s:HOME_DIR:$(pwd):" unittests.ini.dist > unittests.ini
          sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Run unit tests
        run: VIPGOCI_PATH="$HOME/vip-go-ci-tools/vip-go-ci" phpunit --testsuite=unit-tests -vv

  integration-tests:
    name: Run integration tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up PHP environment
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: phpunit:9

      - name: Install tools
        run: ./install.sh

      - name: Remove not needed files
        run: rm -rf ~/vip-go-ci-tools/vip-go-compatibility-scanner ~/vip-go-ci-tools/vip-go-ci

      - name: Set up VIP Go CI
        run: |
          cd ~/vip-go-ci-tools
          wget -O vip-go-ci.tar.gz https://github.com/Automattic/vip-go-ci/archive/trunk.tar.gz
          tar -zxvf vip-go-ci.tar.gz
          mv vip-go-ci-trunk vip-go-ci
          rm -f vip-go-ci.tar.gz

      - name: Prepare files
        run: |
          sed "s:HOME_DIR:$(pwd):" unittests.ini.dist > unittests.ini
          sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Run integration tests
        run: VIPGOCI_PATH="$HOME/vip-go-ci-tools/vip-go-ci" phpunit --testsuite=integration-tests -vv
